main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: iamapikey
    hostname: us.icr.io
    type: icr

  git:
    hostname: github.com
    account: johnwalicki
    username: johnwalicki
    email: johnwalicki@gmail.com
    dev_revision: main

  s3:
    bucket:
      name: rh-industrial-edge
      region: us-east
      message:
        aggregation:
          count: 50
      custom:
        endpoint: s3.us-east.cloud-object-storage.appdomain.cloud
          enabled: false
